---
title: "Draft article"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, echo=FALSE}
library(dplyr)
library(stringr)

data<-read.csv("tiddlers.csv",stringsAsFactors = FALSE)


data<-data %>% filter(str_detect(tags, "\\[")) 
data$tags<-gsub("\\[","",data$tags)
data$tags<-gsub("\\]","",data$tags)
data <- data%>% arrange(tags,title) 

tags<-unique(data$tags)

countTags<-matrix(0,length(tags),3)
countTags[1,1]<-1 
 for (dat in 1:length(tags)){
   thisTag<-as.character(tags[dat])  
   set<-filter(data,tags==thisTag)
   print(thisTag)
   countTags[dat,3]<-nrow(set)
 }


for ( u in 2: length(tags)){
  
   countTags[u,1]<-countTags[u-1,1]+countTags[u-1,3]
  
}

for ( u in 1: length(tags)){
  if (u==1){countTags[1,2]=countTags[1,3]}
  else{  
    countTags[u,2]<-(countTags[u,1]+countTags[u,3]-1)}
  
}


```


```{r echo=FALSE,message=FALSE,results="asis"}
for (t in 1:length(tags)){
  s=countTags[t,1]
  e=countTags[t,2]
thisData<-data[s:e,]
      
        cat("  \n#",  thisData$tags[1], "\n")
        for ( r in 1: nrow(thisData)){
          
        cat("  \n",  thisData$title[r], "\n")
        cat("  \n",  thisData$text[r], "\n")
        cat("  \n")
        
        }
}  
```